name: EA_env
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib  
  - numpy   
  - pip
  - python
  - wheel 
  - scipy
  - tqdm
  - scikit-learn
  - sympy >= 1.9
  - joblib >= 1.1.0
  - notebook
  - swig
  - gymnasium[box2d]